ENVIRONMENT_TYPE: ${self:provider.stage}
JWT_SECRET: KIOSK
JWT_EXPIRATION_TIME: 7d
AWS_REG: ${self:provider.region}
ACCOUNT_ID: 109563118176
DOMAIN_NAME: emopin.com
FROM_EMAIL: admin@emopin.com
MONGODB_URI: ${file(../../${self:provider.stage}.db.json):MONGODB_URI}
MONGODB_NAME: ${file(../../${self:provider.stage}.db.json):MONGODB_NAME}