service: users

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev  #local,dev,prod
  region: ap-south-1
  logRetentionInDays: 14
  environment:
    ${file(../../${self:provider.stage}.environment.yml)}
  versionFunctions: false
  logs:
    restApi: true

package:
 exclude:
   - package.json
   - package-lock.json


custom:
  apiversion: v1

functions:
  apiLogin:
    handler: handler.login
    events:
     - http:
          path: ${self:custom.apiversion}/login
          method: POST
          cors: true
          #authorizer: arn:aws:lambda:us-east-2:406498607568:function:get-adminemails-prod-authorize



plugins:
  - serverless-offline